---
- ansible.builtin.set_fact:
    kibana_virtual_proto: "{{ 'https' if kibana_https_enabled else 'http' }}"

- ansible.builtin.set_fact:
    kibana_validate_certs: "{{ 'no' if kibana_https_self_signed else 'yes' }}"

- name: enable and start kibana
  ansible.builtin.systemd:
    name: kibana 
    state: started 
    enabled: yes

- name: wait kibana to be ready
  ansible.builtin.uri:
    url: "{{ kibana_virtual_proto }}://localhost:{{ kibana_port }}"
    status_code: 200
    follow_redirects: safe
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 30
  delay: 20
  ignore_errors: "{{ ansible_check_mode }}"