---

- shell: uname -s
  register: unames

- shell: uname -m
  register: unamem

- name: add elk group 
  ansible.builtin.group:
    name: "{{ elasticsearch_group }}"
    state: present

- name: add elk user
  ansible.builtin.user:
    name: "{{ elasticsearch_user }}"
    shell: /bin/sh
    password: "*"
    group: "{{ elasticsearch_group }}"

- name: is elk installed
  ansible.builtin.stat:
    path: "{{ elasticsearch_extract_dir }}/elasticsearch-{{ elasticsearch_version }}"
  register: elasticsearch_dir

- ansible.builtin.set_fact:
    elastic_virtual_proto: "{{ 'https' if elasticsearch_https_enabled else 'http' }}"

- name: "Check elasticsearch availability"
  uri:
    url: "{{ elastic_virtual_proto }}://localhost:9200"
    status_code: 401
    validate_certs: no
  register: elk_http_result
  ignore_errors: true

- block:
    - include_tasks:
        file: get_specific_version.yml

    - include_tasks: 
        file: generate_ca.yml
      when: 
        - generateca is defined
        - elasticsearch_security_enabled
        - inventory_hostname in groups['elasticsearch_ca']

    - include_tasks: 
        file: generate_node_cert.yml
      when: 
        - elasticsearch_security_enabled
        - not elasticsearch_use_le_certs

    - include_tasks: 
        file: generate_https_cert.yml
      when: 
        - elasticsearch_https_enabled
        - not elasticsearch_use_le_certs

    - include_tasks: 
        file: keystore_setup.yml
      when: 
        - elasticsearch_security_enabled

  when: 
    - not elasticsearch_dir.stat.exists
    - elk_http_result.status is defined 
    - elk_http_result.status != 401

- include_tasks:
    file: prepare_le_certs.yml
  when:
    - elasticsearch_security_enabled
    - elasticsearch_use_le_certs

- name: Set vm.max_map_count value
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: yes
    state: present
    reload: yes

- name: Render elasticsearch env file
  ansible.builtin.template:
    src: elasticsearch_env.j2
    dest: "{{ elasticsearch_env_file[ansible_os_family] }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0644

- name: Render elasticsearch service file
  ansible.builtin.template:
    src: elasticsearch.service.j2
    dest: /etc/systemd/system/elasticsearch.service
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0644
  notify:
    - reload systemd

- ansible.builtin.set_fact:
    elastic_ip_address: "{{ item }}"
  when:
    - elasticsearch_subnet is defined
    - "item | ansible.utils.ipaddr( elasticsearch_subnet )"
  with_items: "{{ ansible_all_ipv4_addresses }}"

- ansible.builtin.set_fact:
    elastic_ip_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  when:
    - elasticsearch_subnet is not defined

- ansible.builtin.set_fact:
    elastic_iface: "{{ hostvars[inventory_hostname]['ansible_' + item ]['device'] }}"
  when:
    - elasticsearch_subnet is defined
    - "hostvars[inventory_hostname]['ansible_' + item ].ipv4 is defined and hostvars[inventory_hostname]['ansible_' + item ]['ipv4']['address'] | ansible.utils.ipaddr( elasticsearch_subnet )"
  with_items: "{{ ansible_interfaces }}"

- ansible.builtin.set_fact:
    elastic_iface: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['interface'] }}"
  when:
    - elasticsearch_subnet is not defined

- name: Render elasticsearch configuration file
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0644

- name: Render elasticsearch JVM configuration file
  ansible.builtin.template:
    src: jvm.options.j2
    dest: "{{ elasticsearch_conf_dir }}/jvm.options"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0644

- name: Copy elasticsearch log4j configuration file
  ansible.builtin.copy:
    src: log4j2.properties
    dest: "{{ elasticsearch_conf_dir }}/log4j2.properties"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0644