---
- name: Copy Let's encrypt private key in place
  ansible.builtin.copy:
    src: "{{ elasticsearch_local_certs_dir }}/{{ elasticsearch_le_key }}"
    dest: "{{ elasticsearch_certs_dir }}/{{ elasticsearch_le_key }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0644

- name: Copy Let's encrypt full chain cert in place
  ansible.builtin.copy:
    src: "{{ elasticsearch_local_certs_dir }}/{{ elasticsearch_le_fullchain_cert }}"
    dest: "{{ elasticsearch_certs_dir }}/{{ elasticsearch_le_fullchain_cert }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0644